model-name: "stardist_subset-0.50_1-c"
# random-state: 42 # in principle not used anymore as seed args
train-folds:
  - train
valid-folds:
  - valid
samples_pu:
  path: configs/training-samples_subset.json
  positive: subset-0.5-4
  unlabeled: c
