model-name: "stardist_subset-0.25_1-64"
# random-state: 42 # in principle not used anymore as seed args
train-folds:
  - train
valid-folds:
  - valid
samples_pu:
  path: configs/training-samples_subset_64.json
  positive: subset-0.25-0
  unlabeled: 64
